// ── THE IDENTITY THE REACT RENDER MUST ADOPT ─────────────────────────────
//
// Generated by scripts/census-form-identity.mjs and scripts/census-form-filter.mjs.
// A name is here because SOMETHING OUTSIDE THE FORM DEPENDS ON IT: a stylesheet
// rule, a reader in app.js or opportunity-deal-versions.js, or other markup
// inside the form pointing at it (label[for], aria-*).
//
// Names read ONLY by frontend/opportunity-deal.js are deliberately absent: that
// file is what React replaces, so its reads go with it. Testids are separate and
// stay.
//
// THREE THINGS THIS LIST COST, all recorded in the D2d report:
//   1. The census first ran on a form that had never initialised, because the
//      probe used the wrong localStorage key and app.js calls the panel init
//      with an OPTIONAL call that silently does nothing. It reported 143 ids and
//      71 classes of pure static markup, and agreed perfectly with the source.
//      The perfect agreement was the tell: a form that has run adds rows.
//   2. app.js builds 35 DOM lookups by TEMPLATE INTERPOLATION, so a literal
//      scan cannot see them. Measured separately: the only FORM id any of them
//      reaches is opp-tab-commercial, which stays static.
//   3. The stated criterion could not see ids referenced by OTHER MARKUP.
//      Twelve were missing, six of them label[for] targets, and not one was in
//      the list. A label whose input loses its id stops focusing it, silently.

export const ADOPTED_IDS: readonly string[] = [
  "deal-aqm",                      // markup for target
  "deal-bidCurrency",              // read by app.js
  "deal-detail-heading",           // markup aria-labelledby target
  "deal-detail-panel",             // markup aria-controls target
  "deal-factoring-fields",         // style.css rule
  "deal-factoring-ratePct",        // markup for target
  "deal-factoring-termMonths",     // markup for target
  "deal-hemir",                    // markup for target
  "deal-proposalCurrency",         // read by app.js
  "deal-section-3",                // markup aria-controls target
  "deal-section-5",                // markup aria-controls target
  "deal-section-6",                // markup aria-controls target
  "deal-sections-1-2",             // markup aria-controls target
  "deal-ssExisting",               // markup for target
  "deal-ssNew",                    // markup for target
]

export const ADOPTED_CLASSES: readonly string[] = [
  "active",
  "btn-ghost",
  "btn-primary",
  "btn-sm",
  "btn-text",
  "cashflow-scroll",
  "cf-cell",
  "cf-label",
  "cf-row",
  "col-mono",
  "data-row-label",
  "deal-basis",
  "deal-basis-age",
  "deal-basis-label",
  "deal-basis-value",
  "deal-cashflow-col",
  "deal-detail-col",
  "deal-intake-col",
  "deal-panel",
  "deal-payment-col",
  "deal-payment-region",
  "deal-section",
  "deal-section--intake",
  "deal-summary-col",
  "deal-summary-row",
  "deal-toggle",
  "detail-open",
  "disclose",
  "disclose-chevron",
  "dm-cell",
  "dm-cell--span",
  "dm-cell--total",
  "dm-label",
  "dm-row",
  "dm-row--full",
  "dm-row--lead",
  "dm-row--memo",
  "dm-row--sum",
  "doc-table",
  "ds-label",
  "ds-row",
  "ds-value",
  "empty-state",
  "field-note",
  "form-grid",
  "form-group",
  "head",
  "help-dot",
  "hidden",
  "int-only",
  "is-computed",
  "is-scrollable",
  "label",
  "latch",
  "latch-all-row",
  "latch-row",
  "latch-row--intake",
  "msg-error",
  "msg-success",
  "payment-card",
  "payment-terms-panel",
  "pg-card",
  "pg-card-title",
  "pg-cards",
  "pg-cost",
  "pg-head",
  "pg-item-name",
  "pg-item-note",
  "pg-margin-input",
  "pg-price",
  "pg-row",
  "pg-total",
  "po-factoring-panel",
  "po-field",
  "ring-radio",
  "ring-radio-dot",
  "ring-radio-group",
  "ring-radio-label",
  "ring-radio-ring",
  "section-save",
  "section-title",
  "section-title-row",
  "stat-value",
  "stat-value--lead",
  "stats-grid",
  "stats-grid--deal",
  "terms-achieved",
  "terms-cards",
  "terms-field-row",
  "total",
  "under-target",
  "unit-card",
  "unit-cards",
  /* ── RETIRED FROM THIS LIST BY M10, 2026-09-26 ────────────────────────
     Both were adopted from the vanilla's REPAYMENT METHOD control: two
     stacked full-width buttons. John's ruling replaces that control with the
     same two-sided `DealToggle` the mode switch uses, so the deal panel's
     render no longer carries either class.

     THE RATCHET IS NOT RE-OPENED. `KNOWN_MISSING_CLASSES` stays empty: these
     are not classes the render OUGHT to carry and has lost, they are classes
     of a control that no longer exists. Exempting them would have turned a
     closed ratchet into a list of excuses, which is what that comment warns
     against.

     `view-toggle` SURVIVES ELSEWHERE and that is why it is worth saying: the
     version card still uses it, and so does `frontend/index.html`. What ends
     is the DEAL PANEL's use of it, which is what this list is about.
     `view-toggle--stacked` is dead estate-wide, so its stylesheet rules go
     with it - a retirement is two claims (Verification 7). */
  "ys-amount",
  "ys-line",
  "ys-line--total",
  "ys-stack",
  "ys-year",
]
