#!/usr/bin/env node
// ── THE EDIT-ROUTING GUARD ───────────────────────────────────────────────
//
// TWO guards, and the second is the one that did not exist.
//
//   1. IN-FLIGHT: a scripted edit batch that did not fully land. This is the
//      Round 39 guard, unchanged in intent.
//   2. ROUTING: a MODIFIED file in this commit with no journal entry - i.e.
//      an edit that never went through the tool at all.
//
// Guard 2 is why the false-commit-message fault recurred twice. The journal
// used to delete itself on success and the hook opened with
// `[ -f "$JOURNAL" ] || exit 0`, so a routed-and-landed edit and a
// never-routed edit both left nothing and both passed. The guard was
// structurally blind to the case it existed to catch, and "use the tool" was
// left to memory because nothing could enforce it.
//
// ── IT FAILS CLOSED ──────────────────────────────────────────────────────
//
// If it cannot determine whether a modified file was routed, it REFUSES. It
// never passes on "could not tell". A check that passes when unsure is the
// silent failure mode this estate has now killed twice.
//
// ── THE EXEMPTIONS ARE STRUCTURAL, NOT A HABIT ───────────────────────────
//
// Only two kinds of change are exempt, and both are mechanically decided
// from git's own status rather than from anybody's judgement:
//
//   - ADDED files. A creation has no anchor, so it cannot fail the way an
//     edit fails: `cat > file` either writes or errors.
//   - DELETED files. Nothing to land.
//
// Plus a NAMED list of generated artefacts, which live here - in the guard -
// so minting a new exemption is a diff somebody reads (Verification 19).
import { readFileSync, existsSync } from 'node:fs'
import { execFileSync } from 'node:child_process'

const JOURNAL = '.edit-journal.json'

/** Generated by a tool, never hand-edited. Named, not pattern-guessed. */
const GENERATED = [
  'CURRENT_STATE.md',
  'package-lock.json',
  '.edit-journal.json',
]
const GENERATED_DIRS = [
  'frontend-react/dist/',
  // Response fixtures written by the capture scripts named in their own `source`
  // field, never by hand (CLAUDE.md Verification 47, and its Round A extension:
  // the capture is a committed script, and staleness is measured by recapture).
  // Editing one by hand is the fault this whole family exists to prevent, so a
  // routed hand edit would be the wrong thing to make easy.
  'frontend-react/src/__tests__/fixtures/',
]
const isGenerated = (f) =>
  GENERATED.includes(f) || GENERATED_DIRS.some((d) => f.startsWith(d))
  // Probe and census OUTPUTS, which scripts write and nobody edits by hand.
  || (/^scripts\/.*\.json$/.test(f))

const die = (lines) => { for (const l of lines) console.error(l); process.exit(1) }

// ── Read the journal, failing closed on anything unreadable ──────────────
let journal = { label: null, edits: [], landed: [] }
if (existsSync(JOURNAL)) {
  try {
    const j = JSON.parse(readFileSync(JOURNAL, 'utf8'))
    journal = { label: j.label ?? null, edits: j.edits ?? [], landed: j.landed ?? [] }
  } catch (e) {
    die([`COMMIT REFUSED: ${JOURNAL} is present and unreadable.`, `  ${e.message}`])
  }
}

// ── GUARD 1: in-flight edits that did not land ───────────────────────────
const bad = journal.edits.filter((e) => e.status !== 'landed')
if (bad.length) {
  die([
    `COMMIT REFUSED: ${bad.length} scripted edit(s) in batch "${journal.label}" did not land.`,
    '',
    ...bad.flatMap((e) => [`  ${e.file}`, `      status: ${e.status}`,
      ...(e.why ? [`      why:    ${e.why}`] : [])]),
    '',
    'The commit message would have described a change the files do not contain.',
    `Fix the edit, or delete ${JOURNAL} if you have verified the tree by hand.`,
  ])
}

// ── GUARD 2: modified files that never went through the tool ─────────────
let staged = ''
try {
  staged = execFileSync('git', ['diff', '--cached', '--name-status'], { encoding: 'utf8' })
} catch (e) {
  // FAIL CLOSED. Not being able to read the staged set is not permission to pass.
  die(['COMMIT REFUSED: could not read the staged file list, so edit routing',
       'cannot be checked. This guard does not pass on "could not tell".',
       `  ${e.message}`])
}

const modified = staged.trim().split('\n').filter(Boolean)
  .map((l) => l.split(/\t/))
  .filter(([k]) => k && k.startsWith('M'))
  .map(([, f]) => f)
  .filter((f) => !isGenerated(f))

const landed = new Set(journal.landed)
const unrouted = modified.filter((f) => !landed.has(f))

if (unrouted.length) {
  die([
    `COMMIT REFUSED: ${unrouted.length} modified file(s) were not edited through scripts/edit.mjs.`,
    '',
    ...unrouted.map((f) => `  ${f}`),
    '',
    'A hand edit cannot prove it landed, which is how a commit message comes to',
    'describe a change a file does not carry - twice in four rounds.',
    '',
    'Either:',
    "  route the edit:  node scripts/edit.mjs <file> <<'EDIT' ... EDIT",
    '  or, if this file is genuinely generated, add it to GENERATED in',
    '  scripts/hooks/journal-guard.mjs - in a diff somebody reads.',
  ])
}
